### ISSUE TITLE
Update python setup step in workflows to use latest python version

### ISSUE THREAD

**Issue by R-Palazzo** [sdv-dev/SDV#2281]
### Problem Description

In some of our workflows, we use a hardcoded Python version. This means that over time, we have to manually update it.

### Expected behavior
It would be nice to update the python set-up step with something like below so we're always up-to-date
```yml
 - name: Set up latest Python version
      uses: actions/setup-python@v5
      with:
        python-version: 'latest'
```

### Additional context
Here is a list of the worfklows to update:
- static_code_analysis.yml
- release_notes.yml
- lint.yml
- docs.yml
- dependency_checker.yml
